In [1]:
using GeneralNN
using DelimitedFiles
using BenchmarkTools
using DataFrames

In [2]:
pwd()

"/Users/lewis/Code/nn by hand/notebooks"

In [3]:
includet("../src/colconv.jl")

In [4]:
for (mod, file) in Revise.included_files
    Revise.track(mod, file)
end

#### Load some test data to play with

In [5]:
edg = readdlm("../tstdata/edg.csv", ',')

6×6 Matrix{Float64}:
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0

In [6]:
edg_6by6_by3_by1 = reshape(cat(edg, edg,edg,dims=3),(6,6,3,1))

6×6×3×1 Array{Float64, 4}:
[:, :, 1, 1] =
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0

[:, :, 2, 1] =
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0

[:, :, 3, 1] =
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0

In [7]:
v_edge_fil = readdlm("../tstdata/v_edge_fil.csv", ',')

3×3 Matrix{Float64}:
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

In [8]:
v_edge_fil_by3 = reshape(repeat(v_edge_fil, 1,3),3,3,3,1)

3×3×3×1 Array{Float64, 4}:
[:, :, 1, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 2, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 3, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

In [9]:
# now with 3 output channels
v_edge_fil_by3_by3 = reshape(repeat(v_edge_fil, 1, 9),3,3,3,3)

3×3×3×3 Array{Float64, 4}:
[:, :, 1, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 2, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 3, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 1, 2] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 2, 2] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 3, 2] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 1, 3] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 2, 3] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 3, 3] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

In [10]:
h_edge_fil = readdlm("../tstdata/h_edge_fil.csv", ',')

3×3 Matrix{Float64}:
  1.0   1.0   1.0
  0.0   0.0   0.0
 -1.0  -1.0  -1.0

In [11]:
edg2_fil = readdlm("../tstdata/edg2_fil.csv", ',')

6×6 Matrix{Float64}:
 10.0  10.0  10.0   0.0   0.0   0.0
 10.0  10.0  10.0   0.0   0.0   0.0
 10.0  10.0  10.0   0.0   0.0   0.0
  0.0   0.0   0.0  10.0  10.0  10.0
  0.0   0.0   0.0  10.0  10.0  10.0
  0.0   0.0   0.0  10.0  10.0  10.0

In [12]:
same_fil = readdlm("../tstdata/same_fil.csv", ',')

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  0.0

In [13]:
function multiply_fil(x)
x .* [0 0 0;
    0 1 0;
    0 0 0]
end

multiply_fil (generic function with 1 method)

In [14]:
multiply_fil(2.0)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  2.0  0.0
 0.0  0.0  0.0

In [15]:
x = readdlm("../tstdata/x.csv", ',')

6×6 Matrix{Float64}:
 3.0  0.0  1.0  2.0  7.0  4.0
 1.0  5.0  8.0  9.0  3.0  1.0
 2.0  7.0  2.0  5.0  1.0  3.0
 0.0  1.0  3.0  1.0  7.0  8.0
 4.0  2.0  1.0  6.0  2.0  8.0
 2.0  4.0  5.0  2.0  3.0  9.0

In [16]:
schorr = readdlm("../tstdata/schorr_fil.csv", ',')

3×3 Matrix{Float64}:
  3.0  0.0   -3.0
 10.0  0.0  -10.0
  3.0  0.0   -3.0

In [17]:
sobel = readdlm("../tstdata/sobel_fil.csv", ',')

3×3 Matrix{Float64}:
 1.0  0.0  -1.0
 2.0  0.0  -2.0
 1.0  0.0  -1.0

In [18]:
fiva = collect(reshape(1:25, 5, 5)')
sixa = collect(reshape(1:36, 6, 6)')

6×6 Matrix{Int64}:
  1   2   3   4   5   6
  7   8   9  10  11  12
 13  14  15  16  17  18
 19  20  21  22  23  24
 25  26  27  28  29  30
 31  32  33  34  35  36

#### Run some functions

In [19]:
edge_fil_layer3 = ConvLayer(v_edge_fil_by3, [0.2], 1, 1)
display(edge_fil_layer3.weights)

3×3×3×1 Array{Float64, 4}:
[:, :, 1, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 2, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 3, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

In [80]:
conv_inputs3, img_size3 = prep_forward(edge_fil_layer3, edg_6by6_by3_by1)

(conv_inputs = (x_col = [0.0 0.0 … 0.0 0.0; 0.0 10.0 … 0.0 0.0; … ; 10.0 10.0 … 0.0 0.0; 10.0 10.0 … 0.0 0.0], w_col = [1.0; 1.0; … ; -1.0; -1.0;;], bias = [0.2], out_channels = 1, batch_size = 1, out_height = 6, out_width = 6), img_size = (height = 6, width = 6, in_channels = 3, batch_size = 1))

In [21]:
edge_fil_layer33 = ConvLayer(v_edge_fil_by3_by3, [0.2, 0.2, 0.2], 1, 1)

ConvLayer([1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;; 1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;; 1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;;; 1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;; 1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;; 1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;;; 1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;; 1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;; 1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0], [0.2, 0.2, 0.2], 1, 1)

In [91]:
@benchmark prep_forward(edge_fil_layer33, edg_6by6_by3_by1)

BenchmarkTools.Trial: 10000 samples with 10 evaluations.
 Range (min … max):  1.288 μs … 174.996 μs  ┊ GC (min … max):  0.00% … 98.35%
 Time  (median):     1.663 μs               ┊ GC (median):     0.00%
 Time  (mean ± σ):   1.940 μs ±   5.764 μs  ┊ GC (mean ± σ):  13.32% ±  4.48%

   ▁          ▅▄▄█▅▁                                           
  ▅█▆▄▃▂▂▂▂▃▄▇███████▆▅▄▄▃▃▃▃▂▂▂▂▂▁▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▃
  1.29 μs         Histogram: frequency by time        2.74 μs <

 Memory estimate: 9.66 KiB, allocs estimate: 6.

In [86]:
conv_inputs33, img_size33 = prep_forward(edge_fil_layer33, edg_6by6_by3_by1)
# # DataFrame(conv_inputs33.x_col, :auto)
# img_size33

(conv_inputs = (x_col = [0.0 0.0 … 0.0 0.0; 0.0 10.0 … 0.0 0.0; … ; 10.0 10.0 … 0.0 0.0; 10.0 10.0 … 0.0 0.0], w_col = [1.0 1.0 1.0; 1.0 1.0 1.0; … ; -1.0 -1.0 -1.0; -1.0 -1.0 -1.0], bias = [0.2, 0.2, 0.2], out_channels = 3, batch_size = 1, out_height = 6, out_width = 6), img_size = (height = 6, width = 6, in_channels = 3, batch_size = 1))

In [23]:
function debug(col)
    for test_col in 1:5  # first few columns
        for test_row in 1:9  # full window for first channel
            println("col[$test_row, $test_col] = ", col[test_row, test_col])
        end
        println()
    end
end

debug (generic function with 1 method)

In [24]:
debug(conv_inputs33.x_col)

UndefVarError: UndefVarError: `conv_inputs33` not defined

In [82]:
# test col2im
col2im(conv_inputs33.x_col, img_size33, 3,1,1)

6×6×3×1 Array{Float64, 4}:
[:, :, 1, 1] =
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0

[:, :, 2, 1] =
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0

[:, :, 3, 1] =
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0
 10.0  10.0  10.0  0.0  0.0  0.0

In [26]:
for it in conv_inputs33
    println(it)
    println(size(it))
end

UndefVarError: UndefVarError: `conv_inputs33` not defined

In [81]:
f3 = forward_conv(conv_inputs3...)

6×6×1×1 Array{Float64, 4}:
[:, :, 1, 1] =
 -59.8  0.2  60.2  60.2  0.2  0.2
 -89.8  0.2  90.2  90.2  0.2  0.2
 -89.8  0.2  90.2  90.2  0.2  0.2
 -89.8  0.2  90.2  90.2  0.2  0.2
 -89.8  0.2  90.2  90.2  0.2  0.2
 -59.8  0.2  60.2  60.2  0.2  0.2

In [88]:
@benchmark forward_conv(conv_inputs33...)
# f33 = forward_conv(conv_inputs33...)

BenchmarkTools.Trial: 10000 samples with 141 evaluations.
 Range (min … max):  703.901 ns …   3.962 μs  ┊ GC (min … max): 0.00% … 74.27%
 Time  (median):     737.000 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   770.029 ns ± 194.673 ns  ┊ GC (mean ± σ):  1.88% ±  5.80%

   ▂▄▇██▇▆▇▆▅▄▃▃▃▄▃▃▄▃▃▃▂▂▁▂▁▁▂▁▁▂▁▂▂▁ ▁▁ ▁                     ▃
  ▇████████████████████████████████████████▇██▇▇▆▆▇▆▅▄▄▄▄▅▃▄▃▃▅ █
  704 ns        Histogram: log(frequency) by time        975 ns <

 Memory estimate: 2.02 KiB, allocs estimate: 3.

In [29]:
test_conv()

Running forward pass...
Forward pass output shape: (6, 6, 3, 2)

Running backward pass...

Gradient shapes:
dL_dx: (6, 6, 2, 2)
dL_dw: (3, 3, 2, 3)
dL_db: (3,)

All shape checks passed!


true

In [30]:
# test max pooling
pl = PoolLayer(2,2, :mean)
poolout, locations = forward_pool(f33, pl)
@show size(locations)
poolout

UndefVarError: UndefVarError: `f33` not defined

In [31]:
backward_pool(pl, poolout,(6,6,3,1),locations)

UndefVarError: UndefVarError: `poolout` not defined

In [32]:
dL_dx33, dL_dw33, dL_db33 = backward_conv(edge_fil_layer33, f33, img_size33, conv_inputs33)
@show size(dL_dx33)
@show size(dL_dw33)
@show size(dL_db33)

UndefVarError: UndefVarError: `f33` not defined

In [33]:
tst20by3img = zeros(20,20,3)
tst20by3img[:,:,1] .= ones(20,20)
tst20by3img[:,:,2] .= fill(2, 20,20)
tst20by3img[:,:,3] .= fill(3,20,20)
tst20by3img

20×20×3 Array{Float64, 3}:
[:, :, 1] =
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0     1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0 

In [34]:
tst18img = rand(18,18)

18×18 Matrix{Float64}:
 0.0881134  0.676777    0.480706    …  0.750697   0.809443    0.44228
 0.412366   0.631301    0.49138        0.133106   0.914616    0.834437
 0.784264   0.155286    0.243079       0.881591   0.279382    0.130741
 0.371202   0.0746554   0.00741568     0.0934285  0.432301    0.128386
 0.823099   0.0259874   0.749725       0.867014   0.944564    0.965968
 0.878897   0.893831    0.352451    …  0.242571   0.450111    0.64346
 0.435428   0.325272    0.437278       0.815045   0.755899    0.650262
 0.955877   0.0984725   0.740674       0.287817   0.683211    0.987564
 0.97958    0.00472116  0.915768       0.144596   0.455732    0.0182037
 0.0490256  0.0288925   0.709784       0.283579   0.727969    0.312581
 0.972924   0.0169117   0.980513    …  0.650416   0.30429     0.69949
 0.708151   0.390642    0.531154       0.583577   0.216675    0.623533
 0.47738    0.73247     0.851928       0.380757   0.178795    0.669996
 0.144837   0.694514    0.92019        0.816681   0.8917

In [35]:
randfil = rand(5,5)

5×5 Matrix{Float64}:
 0.146592  0.944478  0.868187  0.0521619  0.0677293
 0.152395  0.772871  0.122176  0.943185   0.415284
 0.42803   0.207367  0.128208  0.222298   0.783393
 0.369662  0.752558  0.516789  0.168285   0.0854036
 0.123069  0.551205  0.922088  0.885319   0.956932

In [36]:
minifil = rand(2,2)

2×2 Matrix{Float64}:
 0.00822957  0.400916
 0.447507    0.0353594

#### Multiple input channels, multiple filters convolutional network with 2 layers

In [37]:
filA3by3by5 = zeros(3,3,5)
filA3by3by5[:,:,1] = fill(0.5, 3,3)
filA3by3by5[:,:,2] = fill(0.05, 3,3)
filA3by3by5[:,:,3] = fill(0.005, 3,3)
filA3by3by5[:,:,4] = fill(0.0005, 3,3)
filA3by3by5[:,:,5] = fill(0.00005, 3,3)
filA3by3by5

3×3×5 Array{Float64, 3}:
[:, :, 1] =
 0.5  0.5  0.5
 0.5  0.5  0.5
 0.5  0.5  0.5

[:, :, 2] =
 0.05  0.05  0.05
 0.05  0.05  0.05
 0.05  0.05  0.05

[:, :, 3] =
 0.005  0.005  0.005
 0.005  0.005  0.005
 0.005  0.005  0.005

[:, :, 4] =
 0.0005  0.0005  0.0005
 0.0005  0.0005  0.0005
 0.0005  0.0005  0.0005

[:, :, 5] =
 5.0e-5  5.0e-5  5.0e-5
 5.0e-5  5.0e-5  5.0e-5
 5.0e-5  5.0e-5  5.0e-5

In [38]:
biasA = fill(0.2, 5)

5-element Vector{Float64}:
 0.2
 0.2
 0.2
 0.2
 0.2

In [39]:
filB3by3by5 = zeros(3,3,5)
filB3by3by5[:,:,1] = fill(0.1, 3,3)
filB3by3by5[:,:,2] = fill(0.01, 3,3)
filB3by3by5[:,:,3] = fill(0.001, 3,3)
filB3by3by5[:,:,4] = fill(0.0001, 3,3)
filB3by3by5[:,:,5] = fill(0.00001, 3,3)
filB3by3by5

3×3×5 Array{Float64, 3}:
[:, :, 1] =
 0.1  0.1  0.1
 0.1  0.1  0.1
 0.1  0.1  0.1

[:, :, 2] =
 0.01  0.01  0.01
 0.01  0.01  0.01
 0.01  0.01  0.01

[:, :, 3] =
 0.001  0.001  0.001
 0.001  0.001  0.001
 0.001  0.001  0.001

[:, :, 4] =
 0.0001  0.0001  0.0001
 0.0001  0.0001  0.0001
 0.0001  0.0001  0.0001

[:, :, 5] =
 1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5
 1.0e-5  1.0e-5  1.0e-5

In [40]:
biasB = fill(0.05, 5)

5-element Vector{Float64}:
 0.05
 0.05
 0.05
 0.05
 0.05

##### check dopad with multiple channel image

In [41]:
allpads = padding_same(tst20by3img, filA3by3by5)

UndefVarError: UndefVarError: `padding_same` not defined

In [42]:
dopad(tst20by3img, allpads)

UndefVarError: UndefVarError: `dopad` not defined

In [43]:
conv1out = convolve_multi(tst20by3img, filA3by3by5, biasA)

UndefVarError: UndefVarError: `convolve_multi` not defined

In [44]:
v_edge_fil_3_3_3_1 = cat(v_edge_fil, v_edge_fil, v_edge_fil,dims=3)

3×3×3 Array{Float64, 3}:
[:, :, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 2] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 3] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

In [45]:
v_edge_fil_3_3_3_1 = reshape(v_edge_fil_3_3_3_1, (3,3,3,1))

3×3×3×1 Array{Float64, 4}:
[:, :, 1, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 2, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

[:, :, 3, 1] =
 1.0  0.0  -1.0
 1.0  0.0  -1.0
 1.0  0.0  -1.0

In [46]:
size(edg_6by6_by3_by1)

(6, 6, 3, 1)

In [47]:
size(conv_col_out)

UndefVarError: UndefVarError: `conv_col_out` not defined

In [48]:
clay = ConvLayer(v_edge_fil_3_3_3_1,fill(0.2,3),1,1)

ConvLayer([1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;; 1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;; 1.0 0.0 -1.0; 1.0 0.0 -1.0; 1.0 0.0 -1.0;;;;], [0.2, 0.2, 0.2], 1, 1)

In [49]:
size(clay.weights)

(3, 3, 3, 1)

In [50]:
@benchmark forward(clay, edg_6by6_by3_by1)

UndefVarError: UndefVarError: `forward` not defined

In [51]:
@benchmark x_col, w_col, bias, out_channels, batch_size, out_height, out_width = prep_forward(clay, edg_6by6_by3_by1)

BoundsError: BoundsError: attempt to access @NamedTuple{conv_inputs::@NamedTuple{x_col::Matrix{Float64}, w_col::Matrix{Float64}, bias::Vector{Float64}, out_channels::Int64, batch_size::Int64, out_height::Int64, out_width::Int64}, img_size::@NamedTuple{height::Int64, width::Int64, in_channels::Int64, batch_size::Int64}} at index [3]

In [52]:
@benchmark forward(x_col, w_col, bias, out_channels, batch_size, out_height, out_width)

UndefVarError: UndefVarError: `forward` not defined

In [53]:
img_out1 = forward(x_col, w_col, bias, out_channels, batch_size, out_height, out_width)

UndefVarError: UndefVarError: `forward` not defined

In [54]:
img_out1 = forward(clay, edg_6by6_by3_by1)

UndefVarError: UndefVarError: `forward` not defined

In [55]:
size(img_out1)

UndefVarError: UndefVarError: `img_out1` not defined

In [56]:
@show size(x), size(x_col), size(w_col)

UndefVarError: UndefVarError: `x_col` not defined

In [57]:
img_out1 = col2im(x[:,:,1,1], size(x), 3, 1, 0)

MethodError: MethodError: no method matching col2im(::Matrix{Float64}, ::Tuple{Int64, Int64}, ::Int64, ::Int64, ::Int64)

Closest candidates are:
  col2im(::Matrix{Float64}, !Matched::NamedTuple, ::Int64, ::Int64, ::Int64)
   @ Main ~/Code/nn by hand/src/colconv.jl:86


In [58]:
activ1 = similar(conv1out)
GeneralNN.relu!(activ1, conv1out)

UndefVarError: UndefVarError: `conv1out` not defined

In [59]:
conv2out = convolve_multi(activ1, filB3by3by5, biasB, padding=:none)

UndefVarError: UndefVarError: `convolve_multi` not defined

In [60]:
activ2 = similar(conv2out)
GeneralNN.relu!(activ2, conv2out)

UndefVarError: UndefVarError: `conv2out` not defined

In [61]:
locs = pooling(activ2)[2]

UndefVarError: UndefVarError: `pooling` not defined

In [62]:
#pre-allocate pooling output
activ3 = zeros(9,9,5)
activ3 .= pooling(activ2)[1]

UndefVarError: UndefVarError: `pooling` not defined

In [63]:
size(activ2)

UndefVarError: UndefVarError: `activ2` not defined

In [64]:
activ4 = flatten_img(activ3)

MethodError: MethodError: no method matching flatten_img(::Array{Float64, 3})

Closest candidates are:
  flatten_img(!Matched::Array{Float64, 4})
   @ Main ~/Code/nn by hand/src/colconv.jl:325


In [65]:
size(activ4)

UndefVarError: UndefVarError: `activ4` not defined

In [66]:
wgts5 = rand(200,405)

200×405 Matrix{Float64}:
 0.646883   0.421438   0.142428     …  0.346117   0.482316  0.802152
 0.426532   0.178853   0.84086         0.112768   0.705712  0.0805154
 0.102085   0.0153629  0.190794        0.727624   0.585659  0.556974
 0.596068   0.61783    0.679374        0.446353   0.758449  0.930363
 0.379293   0.431791   0.000495342     0.622339   0.344967  0.437815
 0.472632   0.131828   0.960911     …  0.15644    0.17155   0.741937
 0.378237   0.983458   0.202904        0.101453   0.857301  0.811441
 0.789564   0.75732    0.994583        0.980416   0.210115  0.795127
 0.298385   0.228861   0.5205          0.837007   0.60399   0.0142391
 0.881035   0.307167   0.167078        0.562535   0.740627  0.363101
 ⋮                                  ⋱                       
 0.0472736  0.4342     0.290392        0.917041   0.547251  0.704935
 0.406971   0.574213   0.824196        0.434479   0.510669  0.544984
 0.911642   0.286315   0.425479        0.0340833  0.895915  0.860684
 0.233084   0.3

In [67]:
activ5 = wgts5 * activ4
activ5 = GeneralNN.relu!(activ5, activ5)

UndefVarError: UndefVarError: `activ4` not defined

In [68]:
wgts6 = rand(10,200)

10×200 Matrix{Float64}:
 0.804187   0.546986   0.342474   …  0.204938    0.625381   0.249864
 0.152      0.365376   0.611283      0.373716    0.666272   0.457069
 0.194875   0.0545965  0.892972      0.504166    0.208233   0.403177
 0.599801   0.848794   0.0409828     0.570232    0.394409   0.728875
 0.667175   0.800829   0.921543      0.0265449   0.71511    0.22902
 0.0732125  0.680689   0.750667   …  0.0580188   0.524868   0.0522477
 0.861609   0.901591   0.465569      0.324301    0.509505   0.411188
 0.225395   0.426842   0.0752757     0.11155     0.0257198  0.715908
 0.410488   0.132916   0.612848      0.00758087  0.512784   0.342405
 0.473577   0.399384   0.0142694     0.928063    0.385437   0.452478

In [69]:
z6 = wgts6 * activ5
z6 = reshape(z6,10,1)

UndefVarError: UndefVarError: `activ5` not defined

In [70]:
preds = rand(10,1)

10×1 Matrix{Float64}:
 0.7814277304076037
 0.9986020382440848
 0.7372355132984786
 0.05106643622047713
 0.8278535813283877
 0.21451631293099538
 0.15705277774961146
 0.028280406480288622
 0.7536186092208396
 0.6707493685958246

In [71]:
GeneralNN.softmax!(preds,z6)

UndefVarError: UndefVarError: `z6` not defined

In [72]:
tst = rand(17,17,7);

In [73]:
dopad(tst, (1,1,1,1))

UndefVarError: UndefVarError: `dopad` not defined